Home page and login pages
veereshbv04/BookStore.com-css pull request #2
Opened 2022-03-14 07:42 UTC by veereshbv04

Completed with all the E commerce pages.
Please review and suggest improvements

Live Link : [Link](https://bookstorecss.netlify.app/pages/home.html)

2022-03-14 09:46 UTC, abhisheksahani-nova commented on styles/index.css
> +    max-width: 800px;
Use rem for pixel value more than 10px

2022-03-14 09:46 UTC, abhisheksahani-nova commented on styles/index.css
> +    color: green;
Use css variables

2022-03-14 09:47 UTC, abhisheksahani-nova commented on styles/index.css
> +    color: green;
use css variable everywhere, thats a good practice

2022-03-14 09:48 UTC, abhisheksahani-nova requested changes
Make the suggested changes , else everthing looks great

2022-03-14 14:11 UTC, veereshbv04 commented on styles/index.css
> +    color: green;
yeah will extract colors to root

2022-03-14 14:11 UTC, veereshbv04 commented on styles/index.css
> +    max-width: 800px;
I will change that now

2022-03-14 14:12 UTC, veereshbv04 commented on styles/index.css
> +    color: green;
yeah thanks, i will do that

2022-03-16 00:51 UTC, PrashanthreddyAinala reviewed
Be consistent while using colors, use variables in all places. Rest everything looks good for me.

2022-03-16 07:42 UTC, Prashantrajput11 commented on styles/core.css
> +    --dark-background:grey;
Be consistent with color value notations.

2022-03-16 13:46 UTC, veereshbv04 commented
> Be consistent while using colors, use variables in all places. Rest everything looks good for me.

Yeah I made chaanges and will push them now

2022-03-16 13:52 UTC, merged